
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
import { defineConfig, env } from "prisma/config";
import dotenv from "dotenv";

/**
 * Deliberately not `import "./src/envConfig.js"` (the original generated
 * line) — this file runs in contexts that don't all have a src/ directory
 * next to it. The Docker runtime image ships only build/, no src/, so that
 * relative import threw `Cannot find module './src/envConfig.js'` and took
 * `prisma db push` down with it. dotenv.config() against a missing file is a
 * silent no-op, so this degrades safely wherever DATABASE_URL is already in
 * the environment — every containerised run, since compose injects it via
 * env_file/environment before the process starts — and still loads it from
 * disk for a bare `npm run prisma:push` on a host checkout.
 */
dotenv.config({ path: process.env.NODE_ENV === "production" ? ".env.production" : ".env.development" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
