import { ChatPromptTemplate } from "@langchain/core/prompts";
// import { ChatOllama } from "@langchain/ollama";
import { ChatOpenAI, OpenAIEmbeddings } from "@langchain/openai";
import z from "zod";
import { CATEGORIES } from "../helpers/index.js";

// const statementStructuredSchema = z.object({
//     transactions: z.array(z.object({
//         date: z.string().describe("Transaction Date in ISO format"),
//         description: z.string().describe("Transaction Description"),
//         creditAmount: z.number().describe("Credit Amount"),
//         debitAmount: z.number().describe("Debit Amount"),
//         balance: z.number().describe("Account Balance"),
//     }))
// })

const transactionErrorSchema = z.object({
    errorRows: z.array(z.object({
        action: z.enum(["ACTION_REMOVE", "ACTION_INCORRECT"]),
        rationale: z.string().describe("Reason for why you think that row has some error and what is the error in that row"),
        row: z.array(z.object({
            date: z.string().describe("Transaction Date in ISO format"),
            description: z.string().describe("Transaction Description"),
            creditAmount: z.string().describe("Credit Amount"),
            debitAmount: z.string().describe("Debit Amount"),
            balance: z.string().describe("Account Balance"),
            [process.env.TEMP_ID_KEY || "tempId"]: z.string().describe("Temporary ID to identify the row with error in the original extracted data"),
        })).describe("Row data in key value pair format where key is the column name and value is the corrected value of that column for that row"),
    }))
})

const keyMapperSchema = z.object({
    date: z.string().describe("Key name for Transaction Date in ISO format"),
    description: z.string().describe("Key name for Transaction Description"),
    creditAmount: z.string().describe("Key name for Credit Amount"),
    debitAmount: z.string().describe("Key name for Debit Amount"),
    balance: z.string().describe("Key name for Account Balance"),
})



const normalizerLLM = new ChatOpenAI({
    model: "gpt-5.1",
    temperature: 0,
    // numCtx: 130000,
    // numPredict: 600
    // numThread: 10,
})

// const normalizerLLM = new ChatOllama({
//     model: "llama3.1:8b",
//     temperature: 0,
//     topP: 0.1,
//     maxRetries: 0,
//     // numCtx: 130000,
//     // numPredict: 600
//     // numThread: 10,
// })

const feedbackloopLLMSchema = z.object({
    llmCateory: z.string().describe("New category generated by LLM for the transaction based on the transaction description and other data."),
    rationale: z.string().describe("Rationale for why the new category is more suitable for the transaction than the original category.")
})

const clusterCategorizationLLMSchema = z.object({
    clusterCategory: z.array(z.object({
        merchantName: z.string().nullable().describe("Canonical brand name (e.g. 'Zomato'). Null if no merchant is involved (P2P transfer, salary, EMI, ATM withdrawal, bank charge)."),
        category: z.string().describe("Category from the predefined list."),
        confidence: z.number().describe("Confidence score between 0.0 and 1.0."),
        categorySupportRationale: z.string().describe("One short phrase explaining why this category was chosen.")
    }))
})

const insightsGenllmSchema = z.object({
    spendingAnalysis: z.object({
        categoryBreakdown: z.string().describe("Where money goes each month — mention top categories, amounts, and share of total spend."),
        topMerchants: z.string().describe("Most frequented or highest-spend merchants with amounts and transaction counts."),
        weekdayVsWeekend: z.string().describe("Behavioral spend pattern comparing weekday vs weekend spend and average per transaction."),
        timeOfMonth: z.string().describe("Spend concentration by week of month — highlight any start/end-of-month spikes."),
    }),
    trendAndComparison: z.object({
        monthOverMonth: z.string().describe("Per-category month-over-month change — highlight rising or falling trends."),
        spikeDetection: z.string().describe("Categories where spend jumped significantly vs the 6-month rolling average."),
        seasonalPatterns: z.string().nullable().describe("Quarterly or seasonal spend patterns. Null for Tier 1 and Tier 2."),
    }),
    cashFlow: z.object({
        incomeVsExpenses: z.string().describe("Net cash flow per month — income, expenses, and surplus/deficit."),
        savingsRate: z.string().describe("Savings rate trend across months — is it improving or declining."),
        balanceTrend: z.string().describe("Whether the closing balance is growing or shrinking over time."),
    }),
    recurringExpenses: z.object({
        subscriptions: z.string().describe("Active subscriptions detected — names, amounts, and whether cancellable."),
        emiTracking: z.string().describe("EMI or loan repayments — amounts, frequency, and duration detected."),
        billPatterns: z.string().describe("Utility and phone bills — consistency and combined monthly cost."),
    }),
    anomalyAndRisk: z.object({
        unusualTransactions: z.string().nullable().describe("One-off large debits outside normal behavior. Null for Tier 1 and Tier 2."),
        duplicateDetection: z.string().nullable().describe("Same amount to same merchant twice in a short window. Null for Tier 1 and Tier 2."),
    }),
    behavioralInsights: z.object({
        impulseSpend: z.string().nullable().describe("Small frequent transactions in Food & Dining or Shopping. Null for Tier 1."),
        categoryCreep: z.string().nullable().describe("Categories growing slowly over 3+ months. Null for Tier 1 and Tier 2."),
        refundTracking: z.string().describe("Refunds received — total amount, count, and which categories they came from."),
    }),
})



const structuredLlm = normalizerLLM.withStructuredOutput(transactionErrorSchema);
const keyMapperLlm = normalizerLLM.withStructuredOutput(keyMapperSchema);
const feedbackLoopLlm = normalizerLLM.withStructuredOutput(feedbackloopLLMSchema);
const clusterCategorizationLlm = normalizerLLM.withStructuredOutput(clusterCategorizationLLMSchema);
const insightsGenLlm = normalizerLLM.withStructuredOutput(insightsGenllmSchema);

// const llmSystemMessage = ChatPromptTemplate.fromTemplate(`
//     You are a deterministic error handler.

//     Input is extracted bank table little unstructured JSON data where each key is a page number and value is an array of rows.


//     Task:
//     1. understand the key values and convert them into below keys and only return input to normalized key mapping. Remove any extra keys which are not required and map the existing keys to below mentioned keys. Below is the required key mapping:

//     date → ISO format YYYY-MM-DD
//     description → cleaned single line text
//     creditAmount → number or null
//     debitAmount → number or null
//     balance → number

//     e.g., Date: date, Description: description, Credit Amount: creditAmount, Debit Amount: debitAmount, Balance: balance

//     2. Normalize all the transactions and remove any unwanted keywoerds from description and convert date into ISO format.1


//     DATA:
//     {extractedData}
// `);

// 1. understand the key values and convert them into below keys and only return input to normalized key mapping. Remove any extra keys which are not required and map the existing keys to below mentioned keys. Below is the required key mapping:

//     date → ISO format YYYY-MM-DD
//     description → cleaned single line text
//     creditAmount → number or null
//     debitAmount → number or null
//     balance → number
// e.g., Date: date, Description: description, Credit Amount: creditAmount, Debit Amount: debitAmount, Balance: balance

const llmSystemMessage = ChatPromptTemplate.fromTemplate(`
    You are a deterministic bank transaction error detector and corrector.

    Input:
    JSON array where each object represents one transaction row extracted from a bank statement table.
    Fields: date, description, creditAmount, debitAmount, balance, tempId.

    Goal:
    Identify and fix rows that contain errors. Return ONLY rows that need removal or correction.
    Do NOT include rows that are already correct.

    ── DETECTION RULES ──────────────────────────────────────────────────────────

    1. Merged column values (most common extraction error)
    A field contains two space-separated numbers, e.g. balance = "234.00 23,445.00".
    This means two adjacent PDF columns were merged into one field during extraction.

    The actual column order for this data is:
        {columnOrder}

    Rule: the FIRST space-separated value in a merged field belongs to the column
    immediately BEFORE it in the above sequence. The SECOND value stays in the
    current field.

    Use ACTION_INCORRECT and return the corrected row with values split accordingly.
    Do not use description keywords to decide direction — column order is the only signal.

    2. Amount validation
    • creditAmount and debitAmount cannot both have values in the same row
    • at least one of creditAmount or debitAmount must have a value for a transaction row
    • amount fields must contain a single numeric value (digits, commas, decimal point only)
    • a Cr or Dr suffix on an amount is valid — strip it, do not flag as error

    3. Balance validation
    • balance must be a single numeric value after stripping Cr/Dr suffix.
    • balance must not contain any non-numeric text except for an optional Cr/Dr suffix.
    • if balance contains two space-separated numbers, apply merged column fix (rule 1)

    4. Description validation
    Use ACTION_REMOVE if description:
    • is empty or whitespace only
    • is exactly one of: "balance forward", "opening balance", "closing balance",
      "total", "summary", "statement generated"
    • is a page header or footer repeated from the PDF

    5. Structural validation
    Use ACTION_REMOVE if:
    • row is an opening or closing balance summary line, not an actual transaction
    • row contains only metadata (page number, bank name, account number)

    6. Correction rules for ACTION_INCORRECT
    • split merged column values (rule 1)
    • strip Cr/Dr suffix from amount or balance fields if present
    • if balance contains trailing non-numeric text (e.g. a page footer like "Page 1 of 22"),
      strip everything after the first valid numeric token and keep only that token
    • fix date format if clearly wrong but recoverable
    • clean description: remove leading/trailing whitespace, collapse internal spaces
    • do not alter a value that is already correct

    ── OUTPUT RULES ──────────────────────────────────────────────────────────────
    • Identify incorrect rows and return only corrected rows as per you.
    • Keep tempId unchanged in every corrected row
    • Do not remove any keys from a corrected row — include all fields
    • Prefer ACTION_INCORRECT (fix) over ACTION_REMOVE (delete) whenever fixable
    • Do not flag rows with short but valid descriptions like "GST", "SMS CHARGES",
      "INTEREST CREDIT" — these are legitimate bank transactions
    • Output must be valid JSON with no explanation outside the JSON

    DATA:
    {extractedData}
`);


const llmSystemMessageKeyMapper = ChatPromptTemplate.fromTemplate(`
    You are a deterministic key mapper.

    Input is a list of header names from the extracted bank table. 


    Task:
        1. understand the key values and convert them into below keys and only return input to normalized key mapping. Remove any extra keys which are not required and map the existing keys to below mentioned keys. Below is the required key mapping:

            date → ISO format YYYY-MM-DD
            description → cleaned single line text
            creditAmount → number or null
            debitAmount → number or null
            balance → number
            e.g., Date: date, Description: description, Credit Amount: creditAmount, Debit Amount: debitAmount, Balance: balance

            also, avoid to use special characters in the value mapping and keep it simple and clean. Avoid using multiple words in the key mapping and try to keep it as short as possible while keeping the meaning intact.
            Don't use '#' as a value in the mapping. If you don't know the mapping for any key then map it to "unknown" value.

    Rule:
        1. What DATA will be given in the input those strings should be same as output JSON values. 
            If input is "Deposit (Cr.)" then output "creditAmount: "Deposit (Cr.)". See, output JSON value is same as input string.
    
    DATA:
    {extractedData}
`);

const llmSystemMessageFeedbackLoop = ChatPromptTemplate.fromTemplate(`
    You are a helpful assistant for improving transaction categorization.
    You will be provided with a transaction description and based on existing categories you need to provide new category suggestions.

    
    Existing category: {existingCategory}
    Transaction description: {transactionDescription}
    
`)

const categorySystemMessage = ChatPromptTemplate.fromTemplate(`
        You are a financial transaction classifier for Indian bank statements.

        You will receive a numbered list of transaction clusters. Each cluster has a representative description and a transaction count.
        Classify each cluster and return one result per cluster in the same order.

        Rules:
        - Choose the single best matching category from the list below
        - For merchantName: extract the canonical brand name (e.g. "Zomato", "Uber", "Netflix")
        - Set merchantName to null when there is no identifiable merchant (P2P transfers, salary credits, EMI payments, ATM withdrawals, bank charges)
        - Use "Transfers & Payments" for UPI transfers between people
        - Use "Other" if nothing fits confidently
        - Do not invent or modify category names
        - Return exactly one result per cluster in the same order as input

        Categories:
        ${CATEGORIES.map((c, i) => `${i + 1}. ${c}`).join("\n")}

        Clusters:
        {clusters}
`)

const insightSystemMessage = ChatPromptTemplate.fromMessages([
    ["system", `You are a personal financial analyst generating a spending insight report.
You will receive pre-aggregated monthly statistics. Generate clear, specific, and actionable natural language insights for each section.

Rules:
- Be specific — mention actual months, amounts, and category names
- Do not repeat numbers verbatim — interpret what they mean behaviorally
- Highlight what is surprising, concerning, or worth acting on
- Keep each insight to 2–3 sentences maximum
- Do not give generic advice like "try to save more"
- Currency is Indian Rupees (₹)
- For sections marked null in your tier, return null exactly — do not generate text for them`],
    ["human", `Tier: {tier} | Months of data: {monthsAvailable} | Period: {monthsCovered}

── MONTHLY OVERVIEW ──
{monthlyOverview}

── CATEGORY BREAKDOWN ──
{categoryBreakdown}

── TOP MERCHANTS ──
{topMerchants}

── WEEKDAY VS WEEKEND ──
{weekdayVsWeekend}

── TIME OF MONTH ──
{timeOfMonth}

── RECURRING PATTERNS ──
{recurringPatterns}

── REFUNDS ──
{refunds}

Tier rules:
- Tier 1: set seasonalPatterns, unusualTransactions, duplicateDetection, impulseSpend, categoryCreep to null
- Tier 2: set seasonalPatterns, unusualTransactions, duplicateDetection, categoryCreep to null
- Tier 3: generate all sections`],
])

const embeddingsModel = new OpenAIEmbeddings({
    model: "text-embedding-3-small",
    batchSize: 512,
})



export {
    structuredLlm, llmSystemMessage, llmSystemMessageKeyMapper, keyMapperLlm, embeddingsModel, llmSystemMessageFeedbackLoop, feedbackLoopLlm,
    categorySystemMessage, clusterCategorizationLlm, insightsGenLlm, insightSystemMessage
};
